name: Ejemplo CI Docker (Marketplace)

on:
  push:
    branches: [ "main" ]

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje desde el runner
        run: echo "Este mensaje lo escribe el runner normal"

      - name: Mensaje desde un contenedor Docker (Marketplace)
        uses: docker://alpine:3.18
        with:
          args: echo "Hola, soy un contenedor Docker ejecutado desde una GitHub Action"
