name: Ejemplo CI Docker

on:
  push:
    branches: [ "main" ]

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar versión de Docker
        run: docker --version

      - name: Ejecutar contenedor hello-world
        run: docker run hello-world
